# Generated by Django 3.1.3 on 2020-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201209_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='add name', max_length=100)),
                ('phone', models.IntegerField(default='add number')),
                ('email', models.EmailField(default='abc@edf.com', max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='address',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='video',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.IntegerField(default='add number'),
        ),
    ]
