# Generated by Django 3.1.3 on 2020-12-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201211_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='date_created',
        ),
    ]
