# Generated by Django 3.1.5 on 2021-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_applicant_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Enter the  username', max_length=100)),
                ('password', models.CharField(default='Enter the camera password', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
