# Generated by Django 3.1.5 on 2021-06-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_applicant_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created',
        ),
    ]
