# Generated by Django 3.1.5 on 2021-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_applicant_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='screated',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
