# Generated by Django 3.1.5 on 2021-06-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_applicant_screated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='screated',
        ),
    ]
