# Generated by Django 3.1.5 on 2021-06-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_applicant_screated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='screated',
            field=models.DateTimeField(verbose_name=datetime.date(2021, 6, 22)),
        ),
    ]
