# Generated by Django 3.1.5 on 2021-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210622_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='screated',
            new_name='created',
        ),
    ]
