# Generated by Django 3.1.5 on 2021-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210622_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
