# Generated by Django 3.1.5 on 2021-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210622_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created',
        ),
    ]
